In [2]:
import pandas as pd

In [3]:
customers = pd.read_csv("../data/WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [4]:
customers

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [5]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [9]:
customers["Contract"].unique()

<StringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str

In [11]:
customers["Contract"].value_counts()

Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

In [12]:
customers.isna()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7039,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7040,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7041,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7042,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [22]:
# Inspecting unique values for columns and number of appearances. 
cols = list(customers) 
for c in cols: 
    print(customers[c].value_counts()) 
    print() 
    print("N/A values:") 
    print(customers[c].isna().sum()) 
    print()

customerID
7590-VHVEG    1
5575-GNVDE    1
3668-QPYBK    1
7795-CFOCW    1
9237-HQITU    1
             ..
6840-RESVB    1
2234-XADUH    1
4801-JZAZL    1
8361-LTMKD    1
3186-AJIEK    1
Name: count, Length: 7043, dtype: int64

N/A values:
0

gender
Male      3555
Female    3488
Name: count, dtype: int64

N/A values:
0

SeniorCitizen
0    5901
1    1142
Name: count, dtype: int64

N/A values:
0

Partner
No     3641
Yes    3402
Name: count, dtype: int64

N/A values:
0

Dependents
No     4933
Yes    2110
Name: count, dtype: int64

N/A values:
0

tenure
1     613
72    362
2     238
3     200
4     176
     ...
28     57
39     56
44     51
36     50
0      11
Name: count, Length: 73, dtype: int64

N/A values:
0

PhoneService
Yes    6361
No      682
Name: count, dtype: int64

N/A values:
0

MultipleLines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64

N/A values:
0

InternetService
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

N/A values:
0

OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

N/A values:
0

OnlineBackup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64

N/A values:
0

DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64

N/A values:
0

TechSupport
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64

N/A values:
0

StreamingTV
No                     2810
Yes                    2707
No internet service    1526
Name: count, dtype: int64

N/A values:
0

StreamingMovies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64

N/A values:
0

Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

N/A values:
0

PaperlessBilling
Yes    4171
No     2872
Name: count, dtype: int64

N/A values:
0

PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

N/A values:
0

MonthlyCharges
20.05     61
19.85     45
19.95     44
19.90     44
19.70     43
          ..
72.00      1
108.35     1
63.10      1
44.20      1
78.70      1
Name: count, Length: 1585, dtype: int64

N/A values:
0

TotalCharges
20.2      11
          11
19.75      9
19.9       8
20.05      8
          ..
1990.5     1
7362.9     1
346.45     1
306.6      1
6844.5     1
Name: count, Length: 6531, dtype: int64

N/A values:
0

Churn
No     5174
Yes    1869
Name: count, dtype: int64

N/A values:
0

In [24]:
customers["Churn"].value_counts(normalize=True)

Churn
No     0.73463
Yes    0.26537
Name: proportion, dtype: float64

In [25]:
pd.to_numeric(customers["TotalCharges"])

ValueError: Unable to parse string " " at position 488

In [32]:
empty_values = customers[customers["TotalCharges"] == " "]
print(empty_values)

      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
488   4472-LVYGI  Female              0     Yes        Yes       0
753   3115-CZMZD    Male              0      No        Yes       0
936   5709-LVOEQ  Female              0     Yes        Yes       0
1082  4367-NUYAO    Male              0     Yes        Yes       0
1340  1371-DWPAZ  Female              0     Yes        Yes       0
3331  7644-OMVMY    Male              0     Yes        Yes       0
3826  3213-VVOLG    Male              0     Yes        Yes       0
4380  2520-SGTTA  Female              0     Yes        Yes       0
5218  2923-ARZLG    Male              0     Yes        Yes       0
6670  4075-WKNIU  Female              0     Yes        Yes       0
6754  2775-SEFEE    Male              0      No        Yes       0

     PhoneService     MultipleLines InternetService       OnlineSecurity  ...  \
488            No  No phone service             DSL                  Yes  ...
753           Yes                No              No  No internet service  ...
936           Yes                No             DSL                  Yes  ...
1082          Yes               Yes              No  No internet service  ...
1340           No  No phone service             DSL                  Yes  ...
3331          Yes                No              No  No internet service  ...
3826          Yes               Yes              No  No internet service  ...
4380          Yes                No              No  No internet service  ...
5218          Yes                No              No  No internet service  ...
6670          Yes               Yes             DSL                   No  ...
6754          Yes               Yes             DSL                  Yes  ...

         DeviceProtection          TechSupport          StreamingTV  \
488                   Yes                  Yes                  Yes
753   No internet service  No internet service  No internet service
936                   Yes                   No                  Yes
1082  No internet service  No internet service  No internet service
1340                  Yes                  Yes                  Yes
3331  No internet service  No internet service  No internet service
3826  No internet service  No internet service  No internet service
4380  No internet service  No internet service  No internet service
5218  No internet service  No internet service  No internet service
6670                  Yes                  Yes                  Yes
6754                   No                  Yes                   No

          StreamingMovies  Contract PaperlessBilling  \
488                    No  Two year              Yes
753   No internet service  Two year               No
936                   Yes  Two year               No
1082  No internet service  Two year               No
1340                   No  Two year               No
3331  No internet service  Two year               No
3826  No internet service  Two year               No
4380  No internet service  Two year               No
5218  No internet service  One year              Yes
6670                   No  Two year               No
6754                   No  Two year              Yes

                  PaymentMethod MonthlyCharges  TotalCharges Churn
488   Bank transfer (automatic)          52.55                  No
753                Mailed check          20.25                  No
936                Mailed check          80.85                  No
1082               Mailed check          25.75                  No
1340    Credit card (automatic)          56.05                  No
3331               Mailed check          19.85                  No
3826               Mailed check          25.35                  No
4380               Mailed check          20.00                  No
5218               Mailed check          19.70                  No
6670               Mailed check          73.35                  No
6754  Bank transfer (automatic)          61.90                  No

[11 rows x 21 columns]

In [39]:
# removing rows where total charges has missing value 
# converting total charges to numeric datatype 
customers.drop(customers[customers["TotalCharges"]== " "].index, inplace=True)

In [44]:
customers["TotalCharges"] = pd.to_numeric(customers["TotalCharges"])

In [45]:
customers.info()

<class 'pandas.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   str
 1   gender            7032 non-null   str
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   str
 4   Dependents        7032 non-null   str
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   str
 7   MultipleLines     7032 non-null   str
 8   InternetService   7032 non-null   str
 9   OnlineSecurity    7032 non-null   str
 10  OnlineBackup      7032 non-null   str
 11  DeviceProtection  7032 non-null   str
 12  TechSupport       7032 non-null   str
 13  StreamingTV       7032 non-null   str
 14  StreamingMovies   7032 non-null   str
 15  Contract          7032 non-null   str
 16  PaperlessBilling  7032 non-null   str
 17  PaymentMethod     7032 non-null   str
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.2 MB

In [53]:
y = customers["Churn"] 
X = customers.loc[:, ~customers.columns.isin(['customerID', 'Churn'])]
print(y.shape)
print(X.shape)

(7032,)
(7032, 19)

In [54]:
X.info()

<class 'pandas.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7032 non-null   str
 1   SeniorCitizen     7032 non-null   int64
 2   Partner           7032 non-null   str
 3   Dependents        7032 non-null   str
 4   tenure            7032 non-null   int64
 5   PhoneService      7032 non-null   str
 6   MultipleLines     7032 non-null   str
 7   InternetService   7032 non-null   str
 8   OnlineSecurity    7032 non-null   str
 9   OnlineBackup      7032 non-null   str
 10  DeviceProtection  7032 non-null   str
 11  TechSupport       7032 non-null   str
 12  StreamingTV       7032 non-null   str
 13  StreamingMovies   7032 non-null   str
 14  Contract          7032 non-null   str
 15  PaperlessBilling  7032 non-null   str
 16  PaymentMethod     7032 non-null   str
 17  MonthlyCharges    7032 non-null   float64
 18  TotalCharges      7032 non-null   float64
dtypes: float64(2), int64(2), str(15)
memory usage: 1.1 MB

In [60]:
categorical_columns = X.select_dtypes(include="str").columns
print(categorical_columns)

numerical_columns = X.select_dtypes(exclude="str").columns
print(numerical_columns)

Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='str')
Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges'], dtype='str')

In [85]:
from sklearn.compose import ColumnTransformer 
from sklearn.preprocessing import OneHotEncoder 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

preprocessor = ColumnTransformer(
    transformers = [
        ("categorical", OneHotEncoder(handle_unknown="ignore"), categorical_columns), 
        # ("numerical", "passthrough", numerical_columns)
        ("numerical", StandardScaler(), numerical_columns)
    ])

#X_transformed = preprocessor.fit_transform(X) 
#print(X.shape)
#print(X_transformed.shape) 

# random state for reproducibility
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(5625, 19)
(1407, 19)
(5625,)
(1407,)

In [86]:
# Creating the training pipeline 
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression 

model = Pipeline(
    steps = [
        ("preprocessor", preprocessor), 
        ("classifier", LogisticRegression(max_iter=100)) 
    ]
)

model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('categorical',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='str')),
                                                 ('numerical', StandardScaler(),
                                                  Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges'], dtype='str'))])),
                ('classifier', LogisticRegression())])

In [87]:
# make prediction and calc accuracy and get report 
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

y_pred = model.predict(X_test) 
print(accuracy_score(y_test, y_pred))
print()
print(classification_report(y_test, y_pred, output_dict=True))

0.7874911158493249

{'No': {'precision': 0.8348540145985401, 'recall': 0.8857696030977735, 'f1-score': 0.85955847815876, 'support': 1033.0}, 'Yes': {'precision': 0.6205787781350482, 'recall': 0.516042780748663, 'f1-score': 0.5635036496350365, 'support': 374.0}, 'accuracy': 0.7874911158493249, 'macro avg': {'precision': 0.7277163963667942, 'recall': 0.7009061919232182, 'f1-score': 0.7115310638968982, 'support': 1407.0}, 'weighted avg': {'precision': 0.7778967022763326, 'recall': 0.7874911158493249, 'f1-score': 0.7808630226734206, 'support': 1407.0}}

In [80]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred))

[[916 117]
 [181 193]]